// @ts-ignore
import * as app from '../../bindings/snishaper/app.js';
import { Call, Events } from '@wailsio/runtime';

export const EventsOn = (eventName: string, callback: (data: any) => void) =>
    Events.On(eventName, (event) => callback(event.data));
export const GetAutoStart = () => Call.ByName('main.App.GetAutoStart');
export const SetAutoStart = (enabled: boolean) => Call.ByName('main.App.SetAutoStart', enabled);
export const GetShowMainWindowOnAutoStart = () => Call.ByName('main.App.GetShowMainWindowOnAutoStart');
export const SetShowMainWindowOnAutoStart = (enabled: boolean) => Call.ByName('main.App.SetShowMainWindowOnAutoStart', enabled);
export const GetAutoEnableProxyOnAutoStart = () => Call.ByName('main.App.GetAutoEnableProxyOnAutoStart');
export const SetAutoEnableProxyOnAutoStart = (enabled: boolean) => Call.ByName('main.App.SetAutoEnableProxyOnAutoStart', enabled);
export const {
    AddSiteGroup,
    AddUpstream,
    ClearLogs,
    DeleteECHProfile,
    DeleteSiteGroup,
    DeleteUpstream,
    DisableSystemProxy,
    EnableSystemProxy,
    EnrollWarp,
    ExportCert,
    ExportConfig,
    FetchECHConfig,
    ForceFetchCloudflareIPs,
    GetCACertPEM,
    GetCACertPath,
    GetCAInstallStatus,
    GetCloseToTray,
    GetCloudflareConfig,
    GetCloudflareIPStats,
    GetECHProfiles,
    GetInstalledCerts,
    IsLogCaptureEnabled,
    GetListenPort,
    GetProxyDiagnostics,
    GetProxyMode,
    GetRecentLogs,
    GetServerConfig,
    GetSiteGroups,
    GetStats,
    GetSystemProxyStatus,
    GetUpstreams,
    GetWarpStatus,
    Greet,
    HandleWindowClose,
    ImportConfig,
    ImportConfigWithSummary,
    InstallCA,
    IsProxyRunning,
    OpenCAFile,
    OpenCertDir,
    ProxySelfCheck,
    QuitApp,
    RefreshCloudflareIPPool,
    RegenerateCert,
    RegisterWarp,
    RemoveInvalidCFIPs,
    SetCloseToTray,
    SetListenPort,
    SetProxyMode,
    StartLogCapture,
    StartProxy,
    StartWarp,
    StopLogCapture,
    StopProxy,
    StopWarp,
    TriggerCFHealthCheck,
    UninstallCert,
    UpdateCloudflareConfig,
    UpdateServerConfig,
    UpdateSiteGroup,
    UpdateTrayMenu,
    UpdateUpstream,
    UpsertECHProfile,
    WindowClose,
    WindowMinimise,
    WindowToggleMaximise,
    GetAutoRoutingConfig,
    UpdateAutoRoutingConfig,
    GetAutoRoutingStatus,
    RefreshGFWList,
    TestServerNode
} = app;
