// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import { Call as $Call, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cert$0 from "./cert/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxy$0 from "./proxy/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {proxy$0.SiteGroup} sg
 * @returns {$CancellablePromise<void>}
 */
export function AddSiteGroup(sg) {
    return $Call.ByID(6151454, sg);
}

/**
 * @param {proxy$0.Upstream} u
 * @returns {$CancellablePromise<void>}
 */
export function AddUpstream(u) {
    return $Call.ByID(354377609, u);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearLogs() {
    return $Call.ByID(1566804265);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteECHProfile(id) {
    return $Call.ByID(377029043, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSiteGroup(id) {
    return $Call.ByID(3123351800, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteUpstream(id) {
    return $Call.ByID(1374210559, id);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DisableSystemProxy() {
    return $Call.ByID(3957164446);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function EnableSystemProxy() {
    return $Call.ByID(97511809);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function EnrollWarp() {
    return $Call.ByID(1629644183);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ExportCert() {
    return $Call.ByID(4258689617);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ExportConfig() {
    return $Call.ByID(2222068969);
}

/**
 * @param {string} domain
 * @param {string} dohURL
 * @returns {$CancellablePromise<string>}
 */
export function FetchECHConfig(domain, dohURL) {
    return $Call.ByID(129089643, domain, dohURL);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ForceFetchCloudflareIPs() {
    return $Call.ByID(6639711);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCACertPEM() {
    return $Call.ByID(3220115801);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCACertPath() {
    return $Call.ByID(2279112742);
}

/**
 * @returns {$CancellablePromise<$models.CAInstallStatus>}
 */
export function GetCAInstallStatus() {
    return $Call.ByID(1683651592).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetCloseToTray() {
    return $Call.ByID(3905347684);
}

/**
 * @returns {$CancellablePromise<proxy$0.CloudflareConfig>}
 */
export function GetCloudflareConfig() {
    return $Call.ByID(27116110).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<(proxy$0.IPStats | null)[]>}
 */
export function GetCloudflareIPStats() {
    return $Call.ByID(1013755632).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<proxy$0.ECHProfile[]>}
 */
export function GetECHProfiles() {
    return $Call.ByID(4095379375).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<cert$0.InstalledCert[]>}
 */
export function GetInstalledCerts() {
    return $Call.ByID(4041201978).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetListenPort() {
    return $Call.ByID(3813704531);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetProxyDiagnostics() {
    return $Call.ByID(3318620507).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetProxyMode() {
    return $Call.ByID(1160436438);
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<string>}
 */
export function GetRecentLogs(limit) {
    return $Call.ByID(3603263191, limit);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLogCaptureEnabled() {
    return $Call.ByName("main.App.IsLogCaptureEnabled");
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetServerConfig() {
    return $Call.ByID(1722921122).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @returns {$CancellablePromise<proxy$0.SiteGroup[]>}
 */
export function GetSiteGroups() {
    return $Call.ByID(2843975148).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<[number, number, number]>}
 */
export function GetStats() {
    return $Call.ByID(2859423874);
}

/**
 * @returns {$CancellablePromise<$models.SystemProxyStatus>}
 */
export function GetSystemProxyStatus() {
    return $Call.ByID(1729009524).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<proxy$0.Upstream[]>}
 */
export function GetUpstreams() {
    return $Call.ByID(2333025699).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @returns {$CancellablePromise<proxy$0.WarpStatus>}
 */
export function GetWarpStatus() {
    return $Call.ByID(3490121779).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(2659711170, name);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function HandleWindowClose() {
    return $Call.ByID(329749929);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function ImportConfig(content) {
    return $Call.ByID(3706958138, content);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<proxy$0.ImportSummary>}
 */
export function ImportConfigWithSummary(content) {
    return $Call.ByID(4147028738, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function InstallCA() {
    return $Call.ByID(2320312960);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsProxyRunning() {
    return $Call.ByID(3611198898);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenCAFile() {
    return $Call.ByID(3790942899);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenCertDir() {
    return $Call.ByID(1051130894);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ProxySelfCheck() {
    return $Call.ByID(3433424959);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(3730234565);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RefreshCloudflareIPPool() {
    return $Call.ByID(3614473252);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RegenerateCert() {
    return $Call.ByID(2284126333);
}

/**
 * @param {string} deviceName
 * @returns {$CancellablePromise<string>}
 */
export function RegisterWarp(deviceName) {
    return $Call.ByID(466287078, deviceName);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function RemoveInvalidCFIPs() {
    return $Call.ByID(2070526709);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetCloseToTray(enabled) {
    return $Call.ByID(3218749592, enabled);
}

/**
 * @param {number} port
 * @returns {$CancellablePromise<void>}
 */
export function SetListenPort(port) {
    return $Call.ByID(2173944543, port);
}

/**
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetProxyMode(mode) {
    return $Call.ByID(2478749474, mode);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartProxy() {
    return $Call.ByID(2835838209);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartLogCapture() {
    return $Call.ByName("main.App.StartLogCapture");
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartWarp() {
    return $Call.ByID(1947332473);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopLogCapture() {
    return $Call.ByName("main.App.StopLogCapture");
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopProxy() {
    return $Call.ByID(3345047379);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopWarp() {
    return $Call.ByID(1214049703);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function TriggerCFHealthCheck() {
    return $Call.ByID(3340766504);
}

/**
 * @param {string} thumbprint
 * @returns {$CancellablePromise<void>}
 */
export function UninstallCert(thumbprint) {
    return $Call.ByID(1482241503, thumbprint);
}

/**
 * @param {proxy$0.CloudflareConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCloudflareConfig(cfg) {
    return $Call.ByID(1296358533, cfg);
}

/**
 * @param {string} host
 * @param {string} auth
 * @returns {$CancellablePromise<void>}
 */
export function UpdateServerConfig(host, auth) {
    return $Call.ByID(1415771437, host, auth);
}

/**
 * @param {proxy$0.SiteGroup} sg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSiteGroup(sg) {
    return $Call.ByID(1373443310, sg);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTrayMenu() {
    return $Call.ByID(357427923);
}

/**
 * @param {proxy$0.Upstream} u
 * @returns {$CancellablePromise<void>}
 */
export function UpdateUpstream(u) {
    return $Call.ByID(3803165305, u);
}

/**
 * @param {proxy$0.ECHProfile} p
 * @returns {$CancellablePromise<void>}
 */
export function UpsertECHProfile(p) {
    return $Call.ByName("main.App.UpsertECHProfile", p);
}

/**
 * @returns {$CancellablePromise<proxy$0.AutoRoutingConfig>}
 */
export function GetAutoRoutingConfig() {
    return $Call.ByName("main.App.GetAutoRoutingConfig");
}

/**
 * @param {proxy$0.AutoRoutingConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateAutoRoutingConfig(cfg) {
    return $Call.ByName("main.App.UpdateAutoRoutingConfig", cfg);
}

/**
 * @returns {$CancellablePromise<proxy$0.GFWListStatus>}
 */
export function GetAutoRoutingStatus() {
    return $Call.ByName("main.App.GetAutoRoutingStatus");
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function RefreshGFWList() {
    return $Call.ByName("main.App.RefreshGFWList");
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function TestServerNode() {
    return $Call.ByName("main.App.TestServerNode");
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function WindowMinimise() {
    return $Call.ByName("main.App.WindowMinimise");
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function WindowToggleMaximise() {
    return $Call.ByName("main.App.WindowToggleMaximise");
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function WindowClose() {
    return $Call.ByName("main.App.WindowClose");
}

// Private type creation functions
const $$createType0 = $models.CAInstallStatus.createFrom;
const $$createType1 = proxy$0.CloudflareConfig.createFrom;
const $$createType2 = proxy$0.IPStats.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = proxy$0.ECHProfile.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = cert$0.InstalledCert.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = proxy$0.SiteGroup.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.SystemProxyStatus.createFrom;
const $$createType14 = proxy$0.Upstream.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = proxy$0.WarpStatus.createFrom;
const $$createType17 = proxy$0.ImportSummary.createFrom;
